# Generated by Django 3.0.3 on 2020-02-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
    ]
