# Generated by Django 3.0.3 on 2020-02-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200229_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='label',
            new_name='lavel',
        ),
    ]
