# Generated by Django 3.0.3 on 2020-02-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200229_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='lavel',
            new_name='level',
        ),
    ]
