# Generated by Django 3.0.3 on 2020-02-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200229_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='clevel',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='ctitle',
        ),
        migrations.AlterField(
            model_name='course',
            name='label2',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('6', 'Level 7'), ('8', 'Level 8')], max_length=1),
        ),
    ]
