# Generated by Django 3.0.3 on 2020-03-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200229_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='clevel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ctitle',
            new_name='title',
        ),
    ]
