# Generated by Django 3.0.3 on 2020-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200303_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Abacus', 'Abacus'), ('Vedic Mathematics', 'Vedic Mathematics'), ('Quick Math', 'Quick Math'), ('Unplug Coding', 'Unplug Coding'), ('Python Club', 'Python Club'), ('Electrical and Electronics', 'Electrical and Electronics'), ('Science Club', 'Science Club'), ('Math Club', 'Math Club'), ('English Club', 'English Club'), ('Robotics', 'Robotics'), ('Cyber Literacy', 'Cyber Literacy'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=30)),
                ('label1', models.CharField(choices=[('Top Rated', 'top rated'), ('Bestseller', 'Bestseller')], max_length=20)),
                ('label2', models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8')], max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='CourseDetail1'),
            preserve_default=False,
        ),
    ]
